In [1]:
# Import standard dependencies
import cv2
import os
import uuid
import random
import numpy as np
from matplotlib import pyplot as plt

In [2]:
# Import tensorflow dependencies - Functional API
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Conv2D, Dense, MaxPooling2D, Input, Flatten
import tensorflow as tf

In [ ]:
# Avoid OOM errors by setting GPU Memory Consumption Growth
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus: 
    tf.config.experimental.set_memory_growth(gpu, True)

In [ ]:
os.makedirs('application_data')

In [ ]:
# Setup paths
VER_PATH = os.path.join('application_data', 'verification_images')
INP_PATH = os.path.join('application_data', 'input_image')

In [ ]:
# Make the directories
os.makedirs(VER_PATH)
os.makedirs(INP_PATH)

In [ ]:
# Siamese L1 Distance class
class L1Dist(Layer):
    
    # Init method - inheritance
    def __init__(self, **kwargs):
        super().__init__()
       
    # Magic happens here - similarity calculation
    def call(self, input_embedding, validation_embedding):
        return tf.math.abs(input_embedding - validation_embedding)

In [ ]:
def preprocess(file_path):
    
    # Read in image from file path
    byte_img = tf.io.read_file(file_path)
    # Load in the image 
    img = tf.io.decode_jpeg(byte_img)
    
    # Preprocessing steps - resizing the image to be 100x100x3
    img = tf.image.resize(img, (100,100))
    # Scale image to be between 0 and 1 
    img = img / 255.0

    # Return image
    return img

In [ ]:
# Reload model 
siamese_model = tf.keras.models.load_model('siamesemodelv2_3.h5', 
                                   custom_objects={'L1Dist':L1Dist, 'BinaryCrossentropy':tf.losses.BinaryCrossentropy})

Prepare to take picture for verification images Press P to Take a Picture, Press Q to exit module camera, 50 photos recommended

In [ ]:
# Establish a connection to the webcam
cap = cv2.VideoCapture(0)
while cap.isOpened(): 
    ret, frame = cap.read()
   
    # Cut down frame to 250x250px
    frame = frame[120:120+250,200:200+250, :]
    
    
    # Collect verification_images
    if cv2.waitKey(1) & 0XFF == ord('p'):
        # Create the unique file path 
        imgname = os.path.join(VER_PATH, '{}.jpg'.format(uuid.uuid1()))
        # Write out verification images
        cv2.imwrite(imgname, frame)
    
    # Show image back to screen
    cv2.imshow('Image Collection', frame)
    
    # Breaking gracefully
    if cv2.waitKey(1) & 0XFF == ord('q'):
        break
        
# Release the webcam
cap.release()
# Close the image show frame
cv2.destroyAllWindows()

In [ ]:
os.listdir(os.path.join('application_data', 'verification_images'))

['0c9f5c27-dcef-11ec-914d-04d4c4734f75.jpg',
 '0cbf40cc-dcef-11ec-8f32-04d4c4734f75.jpg',
 '0cdc74d6-dcef-11ec-97d3-04d4c4734f75.jpg',
 '0cfbe450-dcef-11ec-91bc-04d4c4734f75.jpg',
 '0d1bf011-dcef-11ec-bea9-04d4c4734f75.jpg',
 '0d2f7861-dcef-11ec-b7c2-04d4c4734f75.jpg',
 '0d4cc50e-dcef-11ec-af6b-04d4c4734f75.jpg',
 '0d6c828b-dcef-11ec-9398-04d4c4734f75.jpg',
 '0d960463-dcef-11ec-98a1-04d4c4734f75.jpg',
 '0dbd1511-dcef-11ec-8095-04d4c4734f75.jpg',
 '0ddcf9bb-dcef-11ec-9f9c-04d4c4734f75.jpg',
 '0dfa1f33-dcef-11ec-a7ac-04d4c4734f75.jpg',
 '0e19dcf0-dcef-11ec-a0a9-04d4c4734f75.jpg',
 '0e399a67-dcef-11ec-bf6a-04d4c4734f75.jpg',
 '0e4f45b1-dcef-11ec-a5a9-04d4c4734f75.jpg',
 '0e6c923c-dcef-11ec-be94-04d4c4734f75.jpg',
 '0e8a2ceb-dcef-11ec-8f69-04d4c4734f75.jpg',
 '0eb3aebe-dcef-11ec-ac90-04d4c4734f75.jpg',
 '0ee6f4c0-dcef-11ec-9fa5-04d4c4734f75.jpg',
 '0f0e0568-dcef-11ec-ab3d-04d4c4734f75.jpg',
 '0f414b77-dcef-11ec-ab7b-04d4c4734f75.jpg',
 '0f6acd29-dcef-11ec-9f3e-04d4c4734f75.jpg',
 '0f944eee

In [ ]:
os.path.join('application_data', 'input_image', 'input_image.jpg')

'application_data\\input_image\\input_image.jpg'

In [ ]:
for image in os.listdir(os.path.join('application_data', 'verification_images')):
    validation_img = os.path.join('application_data', 'verification_images', image)
    print(validation_img)

application_data\verification_images\0c9f5c27-dcef-11ec-914d-04d4c4734f75.jpg
application_data\verification_images\0cbf40cc-dcef-11ec-8f32-04d4c4734f75.jpg
application_data\verification_images\0cdc74d6-dcef-11ec-97d3-04d4c4734f75.jpg
application_data\verification_images\0cfbe450-dcef-11ec-91bc-04d4c4734f75.jpg
application_data\verification_images\0d1bf011-dcef-11ec-bea9-04d4c4734f75.jpg
application_data\verification_images\0d2f7861-dcef-11ec-b7c2-04d4c4734f75.jpg
application_data\verification_images\0d4cc50e-dcef-11ec-af6b-04d4c4734f75.jpg
application_data\verification_images\0d6c828b-dcef-11ec-9398-04d4c4734f75.jpg
application_data\verification_images\0d960463-dcef-11ec-98a1-04d4c4734f75.jpg
application_data\verification_images\0dbd1511-dcef-11ec-8095-04d4c4734f75.jpg
application_data\verification_images\0ddcf9bb-dcef-11ec-9f9c-04d4c4734f75.jpg
application_data\verification_images\0dfa1f33-dcef-11ec-a7ac-04d4c4734f75.jpg
application_data\verification_images\0e19dcf0-dcef-11ec-a0a9-04d

In [ ]:
def verify(model, detection_threshold, verification_threshold):
    # Build results array
    results = []
    for image in os.listdir(os.path.join('application_data', 'verification_images')):
        input_img = preprocess(os.path.join('application_data', 'input_image', 'input_image.jpg'))
        validation_img = preprocess(os.path.join('application_data', 'verification_images', image))
        
        # Make Predictions 
        result = model.predict(list(np.expand_dims([input_img, validation_img], axis=1)))
        results.append(result)
    
    # Detection Threshold: Metric above which a prediciton is considered positive 
    detection = np.sum(np.array(results) > detection_threshold)
    
    # Verification Threshold: Proportion of positive predictions / total positive samples 
    verification = detection / len(os.listdir(os.path.join('application_data', 'verification_images'))) 
    verified = verification > verification_threshold
    
    return results, verified

Press V to Verif your Face, Please wait, it might not responding

In [ ]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    frame = frame[120:120+250,200:200+250, :]
    
    cv2.imshow('Verification', frame)
    
    # Verification trigger
    if cv2.waitKey(10) & 0xFF == ord('v'):
        # Save input image to application_data/input_image folder 
#         hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
#         h, s, v = cv2.split(hsv)

#         lim = 255 - 10
#         v[v > lim] = 255
#         v[v <= lim] -= 10
        
#         final_hsv = cv2.merge((h, s, v))
#         img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)

        cv2.imwrite(os.path.join('application_data', 'input_image', 'input_image.jpg'), frame)
        # Run verification
        results, verified = verify(siamese_model, 0.5, 0.5)
        print(verified)
    
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 30ms/step
True


If True, than it is your face. You can repeatly press V and see the result

In [ ]:
np.sum(np.squeeze(results) > 0.9)

0

The similarity between input image and verification images

In [ ]:
results

[array([[0.4731445]], dtype=float32),
 array([[0.51513034]], dtype=float32),
 array([[0.53998864]], dtype=float32),
 array([[0.4249946]], dtype=float32),
 array([[0.5352235]], dtype=float32),
 array([[0.57268184]], dtype=float32),
 array([[0.52879727]], dtype=float32),
 array([[0.48781744]], dtype=float32),
 array([[0.4871508]], dtype=float32),
 array([[0.5089126]], dtype=float32),
 array([[0.5284216]], dtype=float32),
 array([[0.47070253]], dtype=float32),
 array([[0.5610992]], dtype=float32),
 array([[0.40965617]], dtype=float32),
 array([[0.5944291]], dtype=float32),
 array([[0.50662005]], dtype=float32),
 array([[0.52387077]], dtype=float32),
 array([[0.5321413]], dtype=float32),
 array([[0.65611976]], dtype=float32),
 array([[0.3754235]], dtype=float32),
 array([[0.6443697]], dtype=float32),
 array([[0.8215317]], dtype=float32),
 array([[0.7034267]], dtype=float32),
 array([[0.847939]], dtype=float32),
 array([[0.726975]], dtype=float32),
 array([[0.5067177]], dtype=float32),
 arr